### ISSUE TITLE
Remember to revoke your DeepL API key

### ISSUE THREAD

**Issue by Avimitin** [du64/scripts#1]
Although you remove your API key in commit https://github.com/du64/scripts/commit/a7f24180b64f70c716952c7b6e826087047517e6, the git history is still kept. It is recommended to rebase your git history and force push to overwrite this history. Besides, remember to revoke your DeepL API key and generate a new one.

To avoid this issue happen again, it is recommended to use a crate like https://github.com/allan2/dotenvy and read the API key from environment variable.

**Comment by z493** [comment]
Got it, thanks for making me aware of the problem. I'll see if I can revoke the API key and get a new one
